Feat : 접속차단 모달, 저장경고 모달 컴포넌트
codeit-sprint-part3-5Bit/part3-project pull request #21
Opened 2024-09-01 07:41 UTC by Happ-yee4831

# 작업분류
- [x] 버그 수정
- [x] 신규 기능
- [x] 리팩토링
- [x] 기타

# 작업개요
- svg파일 위치 변경
- 접속차단 모달 추가
- 저장경고 모달 추가

# 작업 상세 내용
- #18 파일구조 변경에 따라 오류 발생 방지를 위해 미리 closeicon.svg와 lockicon.svg 위치를 변경
- 일정 시간이 지날 경우 수정 중인 내용을 초기화시킬 때 노출시킬 모달창 추가
- 데이터를 저장하지 않고 페이지를 벗어날 시 노출시킬 모달창 추가

# 리뷰 요구사항
- 이후 페이지 작성 중에 추가적으로 수정할 부분을 다시 검토할 예정입니다.

# 기타
#7 #18

2024-09-01 08:24 UTC, SeungHyunOK approved these changes
참고 해서 저두 이쁘게 만들어 보겠습니다! 고생하셧어요!

2024-09-01 08:39 UTC, cwonhyeok approved these changes
고생하셨습니다! 글로 설명하긴 하셨지만 간단하게 어떤 기능이 구현됐는지 이미지가 있으면 더 알기 쉬울거같아여

2024-09-01 14:45 UTC, jangyonghan requested changes
BlockingModal 과 WarningModal이 같은 내용인 것 같은데 확인해주실 수 있을까요?

2024-09-01 14:54 UTC, Happ-yee4831 commented
아직은 모양만 다르고 거의 같은 컴포넌트가 맞습니다! 아무래도 페이지 만들면서 맞춰서 수정해야 할 것 같아서요

2024-09-02 00:05 UTC, jangyonghan approved these changes
넵 알겠습니다!!

2024-09-02 02:04 UTC, merged